// <auto-generated />
using System;
using KampusBag.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KampusBag.Infrastructure.Migrations
{
    [DbContext(typeof(KampusBagDbContext))]
    [Migration("20260312063544_SeedDataMigration")]
    partial class SeedDataMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KampusBag.Core.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademicId")
                        .HasColumnType("uuid");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AcademicId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("51e74f21-cb4d-4854-9a13-b6e3cb65d5c4"),
                            AcademicId = new Guid("fcbe8ad4-0d0f-4a2f-9a41-648c0b4368d4"),
                            CourseCode = "BGM301",
                            Name = "Mobil Programlama (.NET MAUI)"
                        });
                });

            modelBuilder.Entity("KampusBag.Core.Entities.CourseMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRepresentative")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("CourseId", "UserId")
                        .IsUnique();

                    b.ToTable("CourseMemberships");
                });

            modelBuilder.Entity("KampusBag.Core.Entities.EmergencyRight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AcademicTerm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RemainingRights")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("EmergencyRights");
                });

            modelBuilder.Entity("KampusBag.Core.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("IsApprovedByAcademic")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEmergency")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ReceiverId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("KampusBag.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fcbe8ad4-0d0f-4a2f-9a41-648c0b4368d4"),
                            CreatedAt = new DateTime(2026, 3, 12, 6, 35, 43, 967, DateTimeKind.Utc).AddTicks(500),
                            Email = "nihat@gumushane.edu.tr",
                            FullName = "Nihat Özdemir",
                            RegistrationNumber = "SICIL-789",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("907926f4-c384-4a96-9f1e-d5b6da5cee62"),
                            CreatedAt = new DateTime(2026, 3, 12, 6, 35, 43, 967, DateTimeKind.Utc).AddTicks(528),
                            Email = "2411081054@ogr.gumushane.edu.tr",
                            FullName = "Ali Ceylan",
                            RegistrationNumber = "2411081054",
                            Role = 3
                        });
                });

            modelBuilder.Entity("KampusBag.Core.Entities.Course", b =>
                {
                    b.HasOne("KampusBag.Core.Entities.User", "Academic")
                        .WithMany()
                        .HasForeignKey("AcademicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Academic");
                });

            modelBuilder.Entity("KampusBag.Core.Entities.CourseMembership", b =>
                {
                    b.HasOne("KampusBag.Core.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KampusBag.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KampusBag.Core.Entities.EmergencyRight", b =>
                {
                    b.HasOne("KampusBag.Core.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("KampusBag.Core.Entities.EmergencyRight", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KampusBag.Core.Entities.Message", b =>
                {
                    b.HasOne("KampusBag.Core.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sender");
                });
#pragma warning restore 612, 618
        }
    }
}
