// <auto-generated />
using System;
using KampusBag.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KampusBag.Infrastructure.Migrations
{
    [DbContext(typeof(KampusBagDbContext))]
    [Migration("20260312070255_UpdateMessageEntity")]
    partial class UpdateMessageEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KampusBag.Core.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcademicId")
                        .HasColumnType("uuid");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AcademicId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("40849a48-a3a9-402c-bffe-a29737ea59ca"),
                            AcademicId = new Guid("55e6adf8-d4da-4656-bf78-e7d30a489bdb"),
                            CourseCode = "BGM301",
                            Name = "Mobil Programlama (.NET MAUI)"
                        });
                });

            modelBuilder.Entity("KampusBag.Core.Entities.CourseMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRepresentative")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("CourseId", "UserId")
                        .IsUnique();

                    b.ToTable("CourseMemberships");
                });

            modelBuilder.Entity("KampusBag.Core.Entities.EmergencyRight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AcademicTerm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RemainingRights")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("EmergencyRights");
                });

            modelBuilder.Entity("KampusBag.Core.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("IsApprovedByAcademic")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEmergency")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ReceiverId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("KampusBag.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55e6adf8-d4da-4656-bf78-e7d30a489bdb"),
                            CreatedAt = new DateTime(2026, 3, 12, 7, 2, 55, 91, DateTimeKind.Utc).AddTicks(5000),
                            Email = "nihat@gumushane.edu.tr",
                            FullName = "Nihat Özdemir",
                            RegistrationNumber = "SICIL-789",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("a149ece9-3537-4860-bf4d-56a297e50b84"),
                            CreatedAt = new DateTime(2026, 3, 12, 7, 2, 55, 91, DateTimeKind.Utc).AddTicks(5064),
                            Email = "2411081054@ogr.gumushane.edu.tr",
                            FullName = "Ali Ceylan",
                            RegistrationNumber = "2411081054",
                            Role = 3
                        });
                });

            modelBuilder.Entity("KampusBag.Core.Entities.Course", b =>
                {
                    b.HasOne("KampusBag.Core.Entities.User", "Academic")
                        .WithMany()
                        .HasForeignKey("AcademicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Academic");
                });

            modelBuilder.Entity("KampusBag.Core.Entities.CourseMembership", b =>
                {
                    b.HasOne("KampusBag.Core.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KampusBag.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KampusBag.Core.Entities.EmergencyRight", b =>
                {
                    b.HasOne("KampusBag.Core.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("KampusBag.Core.Entities.EmergencyRight", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KampusBag.Core.Entities.Message", b =>
                {
                    b.HasOne("KampusBag.Core.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId");

                    b.HasOne("KampusBag.Core.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Sender");
                });
#pragma warning restore 612, 618
        }
    }
}
